config/routes.rb
Rails.application.routes.draw do
  get 'gists/index'
  root to: 'tests#index'

  resources :feedbacks, only: %i[show new create]
  devise_for :users, :controllers => { :registrations => "users/registrations" },  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get :delete, to: "sessions#delete"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :responses, shallow: true, only: %i[show update]  do
    member do
      get :result
      post :gist
    end
  end

  resources :grants,  shallow: true, only: :index
  resources :badges,  shallow: true, only: :index  

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :feedbacks, only: %i[index destroy]
    resources :badges
    resources :budge_rules
  end
end

app/models/admin.rb
class Admin < User
  
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :max_answers, on: :create

  def max_answers
    err_msg = "Cannot add more then 5 question"
    if (question && question.answers.count >= 5)
      errors.add(:question_id) << err_msg
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :grants
    has_many :users, through: :grants
    has_many :budge_rules
    has_many :rules, through: :budge_rules
end

app/models/budge_rule.rb
class BudgeRule < ApplicationRecord
  belongs_to :badge
  belongs_to :rule

  validates :badge_id, uniqueness: { scope: :rule_id}

  def self.check_badges(response)
    budge_rules = BudgeRule.all
    count_badges = 0
    budge_rules.each do |budge_rule|
      if budge_rule.rule.check_rule(response)
        response.user.grants.create(badge: budge_rule.badge)
        count_badges += 1
      end
    end
    return count_badges
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :test
  has_many :gists

  validates :body, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def completed?
    question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def question_number
    test.questions.index(question) + 1
  end

  def time_remains
    time_finished? ? 0 : test.time_limit.to_i * 60 - time_passed
  end

  def time_limits?
    test.time_limit.to_i > 0
  end

  def time_finished?
    time_limits? ? time_passed > test.time_limit.to_i * 60 : false
  end

  private

  def time_passed
    Time.zone.now.to_i - created_at.to_i
  end

  def before_validation_set_first_question
    self.question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', question.id).first
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :budge_rules
  has_many :badges, through: :budge_rules

  PROC_HASH = {
    'Category' => Proc.new { |response, value| response.test.category.title == value },
    'Attempt' => Proc.new { |response, value|
      Response.where(user_id: response.user.id, test_id: response.test.id).count == value.to_i },
    'Level' => Proc.new { |response, value| response.test.level == value.to_i }
  }

  def check_rule(response)
    return PROC_HASH[name].call(response, value)
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User"
  has_many :responses
  has_many :users, through: :responses
  has_many :questions

  scope :by_level, ->(level) { where(level: level) }
  scope :low, -> { by_level(0..1)}
  scope :middle, -> { by_level(2..4) }
  scope :difficult, -> { by_level(5..Float::INFINITY) }
  scope :by_category, ->(category) { joins(:category)
    .where(categories: { title: category }) }

  validates :title, presence: true
  validates :level, format: { with: /\A[\d]+\z/, message: "Only digits are possible" }
  validates :title, uniqueness: { scope: :level, message:  "Such test already exists" }

  def self.tests_by_category(category)
    by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :responses
  has_many :tests, through: :responses
  has_many :grants
  has_many :badges, through: :grants
  has_many :test, foreign_key: "author_id"
  has_many :gists
  has_many :feedbacks

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def by_level(level)
    tests.by_level(level)
  end

  def current_test(test)
    responses.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :authenticate_user!
  before_action :set_badge, only: %i[destroy show edit update]

  def show
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file_name)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_action :authenticate_user!

  def index
    @badges = Badge.all;
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title.capitalize
    if question.new_record?
      I18n.t('.create_new_question', title: title)
    else
      I18n.t('.edit_question', title: title)
    end
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper

  SUCCESS_RESULT = 85

  def test_result
    @response.correct_questions * 100 / @response.test.questions.count
  end

  def result_success?
    test_result > SUCCESS_RESULT
  end

  def progress_result
    if @response.test.questions.count > 0
      (@response.question_number - 1) * 100 / @response.test.questions.count
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/timer_helper.rb
module TimerHelper

  def timer_string(seconds)
    hour = seconds / 60 / 60
    min = seconds / 60 - hour * 60
    sec = seconds % 60
    hour = "0" + hour.to_s if (hour < 10)
    min = "0" + min.to_s if (min < 10)
    sec = "0" + sec.to_s if (sec < 10)
    hour.to_s + ":" + min.to_s + ":" + sec.to_s
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= badge.file_name %></td>
  <% if File.exist?(Rails.root.join('app','assets','images',badge.file_name))  %>
    <td><%= image_tag("#{badge.file_name}") %></td>
  <% else %>
    <td><%= "#{t('.image_file')} #{badge.file_name} #{t('.not_found')}" %></td>
  <% end %>
  <td><%= link_to t('.edit'), edit_admin_badge_path(badge), class: "btn btn-primary"  %></td>
  <td><%= link_to t('.delete'),
                   admin_badge_path(badge),
                   method: :delete,
                   data: { confirm: t('.are_you_sure') }, class: "btn btn-primary" %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :file_name %><br>
    <%= form.text_field :file_name, id: :badge_file_name %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h2><%= t('.header') %></h2>
    <div class="card border-primary">
      <div class="card-body">
        <%= render 'form' %>
      </div>
      <%= link_to t('.back'), admin_badges_path %>
    </div>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6 ">
    <h1><%= t('.header') %></h1>
    <table class="table">
      <thead>
        <th class="sort-by-title">
          <%= t('.badge') %>
        </th>
        <th><%= t('.file_name') %></th>
        <th><%= t('.image') %></th>
        <th colspan="2"><%= t('.action') %></th>
      </thead>
      <tbody>
        <%= render @badges %>
      </tbody>
    </table>
    <%= link_to t('.new'), new_admin_badge_path %>
    <br>
    <%= link_to t('.rules'), admin_budge_rules_path %>
    <br>
    <%= link_to t('.back'), admin_tests_path %>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1><%= t('.header') %></h1>
    <div class="card border-primary">
      <div class="card-body">
        <%= render 'form' %>
      </div>
      <%= link_to t('.back'), :back %>
    </div>
  </div>
</div>

app/views/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= badge.created_at %></td>
  <% if File.exist?(Rails.root.join('app','assets','images',badge.file_name))  %>
    <td><%= image_tag("#{badge.file_name}") %></td>
  <% else %>
    <td><%= "#{t('.image_file')} #{badge.file_name} #{t('.not_found')}" %></td>
  <% end %>
</tr>

app/views/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6 ">
    <h1><%= t('.header') %></h1>
    <table class="table">
      <thead>
        <th class="sort-by-title">
          <%= t('.badge') %>
        </th>
        <th><%= t('.date') %></th>
        <th><%= t('.image') %></th>
      </thead>
      <tbody>
        <%= render @badges %>
      </tbody>
    </table>
    <%= link_to t('.back'), :back %>
  </div>
</div>