config/routes.rb
Rails.application.routes.draw do
  get 'gists/index'
  root to: 'tests#index'

  resources :feedbacks, only: %i[show new create]
  devise_for :users, :controllers => { :registrations => "users/registrations" },  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get :delete, to: "sessions#delete"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :responses, shallow: true, only: %i[show update]  do
    member do
      get :result
      post :gist
    end
  end

  resources :grants,  shallow: true, only: :index
  resources :badges,  shallow: true, only: :index  

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :feedbacks, only: %i[index destroy]
    resources :badges
    resources :budge_rules
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :max_answers, on: :create

  def max_answers
    err_msg = "Cannot add more then 5 question"
    if (question && question.answers.count >= 5)
      errors.add(:question_id) << err_msg
    end
  end
end

app/controllers/admin/answer_controller.rb
class Admin::AnswersController < Admin::BaseController
  
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('.show'), admin_answer_path(answer) %>
  <%= link_to t('.edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('.delete'),
                   admin_answer_path(answer),
                   method: :delete,
                   data: { confirm: t('.are_you_sure') } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label t('.correct') %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit name=t('.update_answer') %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.editing_answer') %></h1>

<p><%= @answer.question.body %></p>

<%= render 'form' %>
<%= link_to t('.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.new_answer') %></h1>
<p><%= t('.question') %>:</p>
<p>
  <%= @question.body %>
</p>

<%= render 'form', answer: @answer %>
<%= link_to t('.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.answer') %></h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>
<%= link_to t('.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('.back'), admin_question_path(@answer.question) %>