config/routes.rb
Rails.application.routes.draw do
  get 'gists/index'
  root to: 'tests#index'

  resources :feedbacks, only: %i[show new create]
  devise_for :users, :controllers => { :registrations => "users/registrations" },  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get :delete, to: "sessions#delete"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :responses, shallow: true, only: %i[show update]  do
    member do
      get :result
      post :gist
    end
  end

  resources :grants,  shallow: true, only: :index
  resources :badges,  shallow: true, only: :index  

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :feedbacks, only: %i[index destroy]
    resources :badges
    resources :budge_rules
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :test
  has_many :gists

  validates :body, presence: true
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_response, only: %i[show update result gist]
  before_action :time_finished?, only: :update

  def show
  end

  def result
  end

  def update
    answers = params[:answer_ids]
    if (answers)
      @response.accept!(answers)
      if @response.completed?
        TestsMailer.completed_test(@response).deliver_now
        flash.notice = "Поздравляю! У Вас новое достижение!" if BudgeRule.check_badges(@response) > 0
        redirect_to result_response_path(@response)
      else
        render :show
      end
    else
      flash_options = { alert: t('.choice') }
      redirect_to @response, flash_options
    end
  end

  def gist
    service = GistQuestionService.new(@response.question)
    url = service.call
    if service.success?
      flash_options = { notice: t('.success') + ": #{url}" }
      gist = Gist.new(url: url)
      gist.user = current_user;
      gist.question = @response.question
      gist.save
    else
      flash_options = { alert: t('.failed') }
    end

    redirect_to @response, flash_options
  end

  def time_finished?
    if @response.time_finished?
      flash.alert = "Закончилось время прохождения теста"
      redirect_to result_response_path(@response)
    end
  end

  private
  def set_response
     @response = Response.find(params[:id])
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper

  SUCCESS_RESULT = 85

  def test_result
    @response.correct_questions * 100 / @response.test.questions.count
  end

  def result_success?
    test_result > SUCCESS_RESULT
  end

  def progress_result
    if @response.test.questions.count > 0
      (@response.question_number - 1) * 100 / @response.test.questions.count
    end
  end
end

app/views/responses/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.test_was_completed',title: @response.test.title) %></h1>
    <div class="progress">
      <div class="progress-bar bg-warning" role="progressbar" style="width:100%" aria-valuenow="0" aria-valuemin="20" aria-valuemax="100"></div>
    </div>
    <p><%= t('.correct_questions') %>
    <b>
    <% if result_success? %>
       <font color="green"> <%= test_result %>%</font></b>. <%= t('.test_passed') %>
    <% else %>
       <font color="red"> <%= test_result %>%</font></b>. <%= t('.test_not_passed') %>
    <% end %>
    </p>
    <%= link_to t('.tests'), tests_path %>
  </div>
</div>

app/views/responses/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.passing_the_test',title: @response.test.title) %></h1>
    <h3><%= t('.question_number_all_questions', current_number: @response.question_number,
      count: @response.test.questions.count) %>
    </h3>
    <div class="progress">
      <div class="progress-bar bg-warning" id="progress" role="progressbar" style="width: 15" aria-valuenow="0" aria-valuemin="20" aria-valuemax="100" data-progress-percent=<%= progress_result %>></div>
    </div>
    <span id="my_timer" data-time-limit=<%= @response.time_remains %> style="font-weight: bold;">
      <% if @response.time_limits? %>
        <%= timer_string(@response.time_remains) %>
      <% end %>
    </span>
    <div class="card">
      <div class="card-header">
         <b> <%= @response.question.body %> </b>
      </div>
      <ul class="list-group list-group-flush">
        <%= form_with url: response_path(@response), local: true, method: :put do |form| %>
          <%= form.collection_check_boxes :answer_ids, @response.question.answers, :id, :body, include_hidden: false do |b| %>
            <li class="list-group-item">
              <%= b.check_box id: "answer_ids_#{b.object.id}" %>
              <%= b.label %>
            </li>
          <% end %>
      </ul>
        <%= link_to t('.gist_question'), gist_response_path(@response), method: :post %>
        <%= form.submit t('.next'), class: "next_button btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>